# Generated by Django 3.2.5 on 2021-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
